name: image_search_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  go_router: ^15.0.0
  http: ^1.3.0
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  analyzer: ^6.9.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
